class UnitType:

    def __init__(self, json):
        self.ID             = json['ID']         
        self.name           = json['name']
        self.cost           = json['cost']
        self.hp             = json['hp']
        self.minDamage      = json['minDamage']
        self.maxDamage      = json['maxDamage']
        self.attackRange    = json['attackRange']
        self.produceTime    = json['produceTime']
        self.moveTime       = json['moveTime']
        self.attackTime     = json['attackTime']
        self.harvestTime    = json['harvestTime']
        self.returnTime     = json['returnTime']
        self.harvestAmount  = json['harvestAmount']
        self.sightRadius    = json['sightRadius']
        self.isResource     = json['isResource']
        self.isStockpile    = json['isStockpile']
        self.canHarvest     = json['canHarvest']
        self.canMove        = json['canMove']
        self.canAttack      = json['canAttack']
        self.produces       = json['produces']
        self.producedBy     = json['producedBy']